#!/usr/local/bin/zsh
# Copyright (c) 2011 Tristan Le Guern <tristan.le-guern@epitech.eu>
#
# Permission to use, copy, modify, and distribute this software for any                                                                                                             
# purpose with or without fee is hereby granted, provided that the above                                                                                                            
# copyright notice and this permission notice appear in all copies.                                                                                                                 
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES                                                                                                        
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF                                                                                                                  
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR                                                                                                           
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES                                                                                                            
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN                                                                                                             
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF                                                                                                           
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                                                                                                    

emulate -L zsh
setopt no_sh_word_split null_glob no_ksh_arrays
zmodload zsh/net/tcp

function zs_parse_option {
	o_location=(-l "Dans ton cul")
	o_data=(-m "zsh est cool")
	o_log=(-o /tmp/zsoul.log)
	o_port=(-p 4242)
	o_server=(-s "ns-server.epita.fr")
	debug=0
	
	zparseopts -K -- p:=o_port s:=o_server o:=o_log l:=o_location \
		x:=o_data h=o_help f:=o_conf d=o_debug
	
	if [[ $? != 0 || "$o_help" != "" ]]; then
		echo Usage: $(basename "$0") "[-hd] [-s SERVER] [-p PORT] [-o LOGFILE] [-l LOCATION] [-m DATA]"
		exit 64 #EX_USAGE
	fi

	if [[ "$o_debug" != "" ]] debug=1
	
	port=$o_port[2]
	server=$o_server[2]
	logfile=$o_log[2]
	data=$o_data[2]
	location=$o_location[2]
}

function zs_print_log {
	print $1 >> $logfile
}

function zs_connect {
	#XXX: Error handling
	ztcp $server $port
	fd=$REPLY
	read -r ns_reply <&$fd
	# ns_ret is an array with usefull values for authentification
	ns_ret=( $(echo $ns_reply | cut -d ' ' -f 3,4,5) )
}

function zs_init_auth {
	echo auth_ag ext_user none none >&$fd
	read -r ns_reply <&$fd
}

#function zs_hash {
#	echo `md5 -s "${ns_ret[1]}-${ns_ret[2]}/${ns_ret[3]}$SOCKS_PASSWORD" | cut -d ' ' -f 4`
#}

function zs_auth {
	zs_init_auth	; if [[ $debug -eq 1 ]] print -r - $ns_reply

	local hash=`md5 -s "${ns_ret[1]}-${ns_ret[2]}/${ns_ret[3]}$SOCKS_PASSWORD" | cut -d ' ' -f 4`
	print ext_user_log $SOCKS_USERNAME $hash "toto" "cul" >&$fd
	read -r ns_reply <&$fd
}

zs_parse_option $@
zs_connect 	; if [[ $debug -eq 1 ]] print -r - $ns_reply
zs_auth		; if [[ $debug -eq 1 ]] print -r - $ns_reply

ztcp -c $fd
